import { ENV_CONFIG } from './env.config';

export const APP_CONFIG = {
  NUM_QUARTERS: ENV_CONFIG.NUM_QUARTERS,
  CACHE_MAX_AGE: ENV_CONFIG.CACHE_MAX_AGE,
  API_TIMEOUT: ENV_CONFIG.API_TIMEOUT,
  USER_AGENT: ENV_CONFIG.USER_AGENT
};
